"""Main interface for C++ kernel symbols."""

from __future__ import annotations

import enum
from typing import Sequence

from typing_extensions import Buffer

class Dtype(enum.Enum):
    """C++-side storage types."""

    Bool = 0
    Int32 = 1
    Int64 = 2
    Float32 = 3
    Float64 = 4

    def __eq__(self, value: object) -> bool: ...
    def __le__(self, value: object) -> bool: ...
    def __lt__(self, value: object) -> bool: ...
    def __ge__(self, value: object) -> bool: ...
    def __gt__(self, value: object) -> bool: ...

class Storage(Buffer):
    """Pointer to a 1D contiguous, typed memory segment."""
    @staticmethod
    def allocate(n: int, dtype: Dtype) -> Storage: ...
    @staticmethod
    def from_iterable(s: Sequence[bool | int | float], dtype: Dtype) -> Storage: ...
    @property
    def size(self) -> int: ...
    @property
    def itemsize(self) -> int: ...
    @property
    def dtype(self) -> Dtype: ...
    def clone(self) -> Storage: ...
    def cast(self, dtype: Dtype) -> Storage: ...

class TensorView:
    """C++ representation of a strided tensor."""
    def __init__(
        self,
        storage: Storage,
        shape: tuple[int, ...],
        strides: tuple[int, ...],
        offset: int,
    ) -> None: ...

# Factories
def zeros(shape: tuple[int, ...], dtype: Dtype) -> Storage: ...
def ones(shape: tuple[int, ...], dtype: Dtype) -> Storage: ...
def full(
    shape: tuple[int, ...], value: bool | int | float, dtype: Dtype
) -> Storage: ...
def eye(n: int, dtype: Dtype) -> Storage: ...
def arange(n: int, start: int, step: int, dtype: Dtype) -> Storage: ...

# Ops
# s: storage / sh: shape / st: strides / of: offset
def sum(x: TensorView, axis: Sequence[int], keepdim: bool, dtype: Dtype) -> Storage: ...
def add(x1: TensorView, x2: TensorView) -> Storage: ...
def subtract(x1: TensorView, x2: TensorView) -> Storage: ...
def multiply(x1: TensorView, x2: TensorView) -> Storage: ...
def divide(x1: TensorView, x2: TensorView) -> Storage: ...
def matmul(x1: TensorView, x2: TensorView) -> Storage: ...
def exp(x1: TensorView) -> Storage: ...
def log(x1: TensorView) -> Storage: ...
def pow(x1: TensorView, power: float) -> Storage: ...
def neg(x1: TensorView) -> Storage: ...
def equals(x: TensorView, y: TensorView) -> bool: ...
def relu(x: TensorView) -> Storage: ...
def pw_equal(x: TensorView, s: TensorView) -> Storage: ...
def pw_greater(x: TensorView, s: TensorView) -> Storage: ...
def pw_greater_eq(x: TensorView, s: TensorView) -> Storage: ...

# Inplace
def add_inplace(x1: TensorView, x2: TensorView) -> None: ...
def sub_inplace(x1: TensorView, x2: TensorView) -> None: ...
def mul_inplace(x1: TensorView, x2: TensorView) -> None: ...
def div_inplace(x1: TensorView, x2: TensorView) -> None: ...
def copy_inplace(x1: TensorView, x2: TensorView) -> None: ...

# Core ops
def cast(s: Storage, dtype: Dtype) -> Storage: ...
def copy_view(*, src: TensorView, dst: TensorView) -> Storage: ...
def scatter_to_axes(
    *,
    src: TensorView,
    dst: TensorView,
    fancy_dims_in_src: Sequence[int],
    fancy_dims_data: Sequence[TensorView],
    out_axis_is_fancy: Sequence[bool],
    out_axis_target: Sequence[int],
) -> Storage: ...
def gather_from_axes(
    *,
    x: TensorView,
    new_sh: tuple[int, ...],
    fancy_dims_in_src: Sequence[int],
    fancy_dims_data: Sequence[TensorView],
    out_axis_is_fancy: Sequence[bool],
    out_axis_target: Sequence[int],
) -> Storage: ...
