import enum
from typing import Sequence

class Dtype(enum.Enum):
    """C++-side storage types."""

    Bool = 0
    Int32 = 1
    Int64 = 2
    Float32 = 3
    Float64 = 4

# Layout contract: flattened array representations
class Storage:
    @staticmethod
    def allocate(n: int, dtype: Dtype) -> "Storage": ...
    @staticmethod
    def from_iterable(s: Sequence[bool | int | float], dtype: Dtype) -> "Storage": ...
    @property
    def size(self) -> int: ...
    @property
    def itemsize(self) -> int: ...
    @property
    def dtype(self) -> Dtype: ...
    def clone(self) -> "Storage": ...
    def cast(self, dtype: Dtype) -> "Storage": ...

def cast(buffer: Storage, dtype: Dtype) -> Storage: ...
def equals(buffer1: Storage, buffer2: Storage) -> bool: ...
def sum(buffer: Storage) -> float: ...
